#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scala-xml_2.12
Version  : 1
Release  : 1
URL      : https://repo.maven.apache.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.5/scala-xml_2.12-1.0.5.jar
Source0  : https://repo.maven.apache.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.5/scala-xml_2.12-1.0.5.jar
Source1  : https://repo.maven.apache.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.5/scala-xml_2.12-1.0.5.pom
Source2  : https://repo.maven.apache.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar
Source3  : https://repo.maven.apache.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-scala-xml_2.12-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-scala-xml_2.12 package.
Group: Data

%description data
data components for the mvn-scala-xml_2.12 package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.5
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.5/scala-xml_2.12-1.0.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.5
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.5/scala-xml_2.12-1.0.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.6
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.6
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.5/scala-xml_2.12-1.0.5.jar
/usr/share/java/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.5/scala-xml_2.12-1.0.5.pom
/usr/share/java/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar
/usr/share/java/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.pom
